
sticks 3

[BUTTON_EXECUTE]
0 	fire
1	lock
2 	backleft
3	backright
4   left
5   right
6   outefront
7   innterfront
8   outermiddle
9   innermiddle
10  outerback
11  innerback

# main
[STICK0]
axes 2
axis0_id 0
invert_axis_0  false
axis1_id 1
invert_axis_1  true
deadZone	0.02

# tilt
[STICK1]
axes 1
axis0_id 2
invert_axis_0  false
deadZone	0.05

# throttle
[STICK2]
axes 1
axis0_id 3
invert_axis_0  true
deadZone	0.05

# hat
# see header YARP\src\libYARP_dev\src\yarp\dev\IJoypadController.h
# #define YRPJOY_HAT_CENTERED     0x00
# #define YRPJOY_HAT_UP           0x01
# #define YRPJOY_HAT_RIGHT        0x02
# #define YRPJOY_HAT_DOWN         0x04
# #define YRPJOY_HAT_LEFT         0x08
# #define YRPJOY_HAT_RIGHTUP      (YRPJOY_HAT_RIGHT|YRPJOY_HAT_UP)
# #define YRPJOY_HAT_RIGHTDOWN    (YRPJOY_HAT_RIGHT|YRPJOY_HAT_DOWN)
# #define YRPJOY_HAT_LEFTUP       (YRPJOY_HAT_LEFT |YRPJOY_HAT_UP)
# #define YRPJOY_HAT_LEFTDOWN     (YRPJOY_HAT_LEFT |YRPJOY_HAT_DOWN)